### ISSUE TITLE
关于截图函数的一个疑问

### ISSUE THREAD

**Issue by nazhendenb** [NeutrinoC/Auto_GirlsFrontline#11]
昨天重装系统了，我也不知道是哪个模块的问题（盲猜win32api）。

已知：使用mumu模拟器，分辨率750x500的意思是指游戏窗口的分辨率是750x500，Y轴方向并不包含模拟器边框，如图，用QQ截图得到游戏本体分辨率是750x500 。 但是我在尝试魔改凸洞打捞的时候遇到了我期望之外的情况。

![image](https://user-images.githubusercontent.com/36919867/90998813-92280300-e5f7-11ea-8848-798791918681.png)

情况如下：调用test.py（截图函数），把截图区域改成[0,0,1,1]，他截到的图是包含模拟器边框的（我期望得到的返回值是图1的蓝色矩形区域），我记得自己之前修改拆解函数的时候按照的是游戏窗口的相对坐标，即不包含模拟器边框，请问这种情况是某个模块（库）更新导致的变化吗？还是说我之前就有问题？ 顺便问一下大佬是如何获取相对坐标的？

![image](https://user-images.githubusercontent.com/36919867/90998444-b3d4ba80-e5f6-11ea-8e1c-692231bbaa8e.png)

最后是一人血书求血潮逐浪捞枪脚本，2战2判直接结算，活动持续一个月，改不了吃亏，改不了上当（我编不下去了，救救孩子。）

**Comment by NeutrinoC** [comment]
截图的时候相对坐标一直是对应整个模拟器界面的，你看我之前的程序都有一个功能就是把游戏关掉重启，那个就是点游戏标签页的叉叉来关掉游戏的。相对坐标是自己一点一点估计出来的，在test.py里面不是会把截的图显示出来吗，就是用来截一下调一下的，直到满意为止。
秃洞捞枪我试了一下，感觉还行，这几天我弄一个吧。

**Comment by nazhendenb** [comment]
> 截图的时候相对坐标一直是对应整个模拟器界面的，你看我之前的程序都有一个功能就是把游戏关掉重启，那个就是点游戏标签页的叉叉来关掉游戏的。相对坐标是自己一点一点估计出来的，在test.py里面不是会把截的图显示出来吗，就是用来截一下调一下的，直到满意为止。
> 秃洞捞枪我试了一下，感觉还行，这几天我弄一个吧。

先谢过大佬。等好消息

**Comment by nazhendenb** [comment]
> 截图的时候相对坐标一直是对应整个模拟器界面的，你看我之前的程序都有一个功能就是把游戏关掉重启，那个就是点游戏标签页的叉叉来关掉游戏的。相对坐标是自己一点一点估计出来的，在test.py里面不是会把截的图显示出来吗，就是用来截一下调一下的，直到满意为止。
> 秃洞捞枪我试了一下，感觉还行，这几天我弄一个吧。

 我自己试着做了一个，下午测了十几把没什么大问题，大佬有兴趣捧个场吧。 文件名忘了改，  运行 auto8_1n2.py即可。
 链接:https://pan.baidu.com/s/1fM-apACwmLIfZhxQNppUZw 提取码:rndu 

下面是一些废话：
1.吃个饭回来发现停住了，因为我是以炸狗为模板改的，所以仓库满了是强化人形，而原模板是强化装备，所以卡住是正常的。 吃完饭又做了重启功能，如果检测到断线的话就直接结算
2.每次进去都要缩放地图，目前想不到什么好的解决方案，加全局计数器感觉也不行，断线的话又要重置计数，感觉好麻烦。（其实主要是我菜）  ，速度方面大概是130秒一轮。 500个星星要十个小时（好难啊）
3.拆解函数我改成了先自动拆解一次（拆掉2星），然后拆一排3星。 应该够用了（管不住手老是把钻买成币抽皮肤）。
4.我用的是丝巾+3改M4，有战损，但是吧..那个伤害我估计刷一晚上也不会死，就没加修复。 朋友说火力HG+AN94可以无伤，可惜我没AN94
5.对原函数做了大量修改，虽然有注释，但是可读性变得极差。（估计明天我就看不懂了。）
6.我这个版本就是凑合着用，还是期待大佬的官方版本。 
7. 感觉GitHub交流效率太低了，不如加个好友吧。 956113681

**Comment by NeutrinoC** [comment]
不错哟，你可以把程序上传到自己的github项目的

还有就是个人信息还是不要随意透露了，我怕被人冲了，你放心，我经常地会看github地消息的
