### ISSUE TITLE
关于如何获得图片的相对位置坐标的一些请教

### ISSUE THREAD

**Issue by Flandre923** [NeutrinoC/Auto_GirlsFrontline#16]
我看了你代码后，想写个一个其他游戏的代码，但是发现，在获得截图时候不知道什么好的方法来找区域的截图，是相对位置的坐标，作者有什么建议吗。或者你是怎么做的

**Comment by NeutrinoC** [comment]
我不太明白你所说的”不知道什么好的方法来找区域的截图“是指的什么，如果是只是要截图的，随便一个test.py里都有，如果是要找位置的话，我是用的比较原始的办法，截一下调一下截一下调一下，如果想要自主定位的话你可以试试怎么把yolo塞进去

**Comment by Flandre923** [comment]
> 我不太明白你所说的”不知道什么好的方法来找区域的截图“是指的什么，如果是只是要截图的，随便一个test.py里都有，如果是要找位置的话，我是用的比较原始的办法，截一下调一下截一下调一下，如果想要自主定位的话你可以试试怎么把yolo塞进去

我觉得截一下调一下太麻烦了，就想问问，有没有其他方面，谢谢啦~

**Comment by NeutrinoC** [comment]
确实是很麻烦，不过我能力有限只能做成这个样子
