### ISSUE TITLE
打开之后报错闪退

### ISSUE THREAD

**Issue by CZheXie** [NeutrinoC/Auto_GirlsFrontline#2]
![)A{T1T}@47 RZ8%P~ZL)2L6](https://user-images.githubusercontent.com/37114944/75871051-ede2b200-5e46-11ea-8440-a24d2b9f7aa0.png)
我把图片都重新预存过
网易UU模拟器800X400
Input images must have the same dimensions
指的是什么需要相同尺寸?

**Comment by NeutrinoC** [comment]
这个就是截取的图和你预存的图尺寸不对，建议从以下几点查错：
1. 预存的图片时，模拟器大小是否是800*400
2. 单独运行autoJS9.py中的getWindowData()，把返回值打印一下，我这边返回值是这样的：[510, 117, 1310, 606, 800, 489]，核对一下最后两个值，确认模拟器窗口大小无误
3. 如果以上都没问题，尝试使用我预存图片

**Comment by NeutrinoC** [comment]
如果还是有问题，可以加我的qq:1352295602，方便交流差错
