### ISSUE TITLE
[建议]关于模拟点击的一些建议

### ISSUE THREAD

**Issue by Evicce** [NeutrinoC/Auto_GirlsFrontline#3]
2.0.22版本mumu可以通过win32gui.SendMessage实现最小化模拟器窗口的情况下进行模拟点击，老哥有空可以改一下试试

**Comment by NeutrinoC** [comment]
老哥你的想法非常的好，但是有一个难点，程序最小化了之后没法抓取图片了

**Comment by Evicce** [comment]
关于截图的话经测试pyqt5可以在窗口被遮挡的情况下截取到窗口，这样也能在脚本运行的时候做别的事了，总之我先改着试试看吧。

> 老哥你的想法非常的好，但是有一个难点，程序最小化了之后没法抓取图片了

**Comment by GiGaFotress** [comment]
> 关于截图的话经测试pyqt5可以在窗口被遮挡的情况下截取到窗口，这样也能在脚本运行的时候做别的事了，总之我先改着试试看吧。
> 
> > 老哥你的想法非常的好，但是有一个难点，程序最小化了之后没法抓取图片了

想当懒狗的话用auto.js，手机扔一边让跑就完事了，我倒是在想怎么反检测

**Comment by ChineseBeanLin** [comment]
感觉可以试试adb，这样后台截图和点击都比较容易实现

**Comment by GiGaFotress** [comment]
> 感觉可以试试adb，这样后台截图和点击都比较容易实现

ADB会引起检测，USB调试过于明显

**Comment by ChineseBeanLin** [comment]
> > 感觉可以试试adb，这样后台截图和点击都比较容易实现
> 
> ADB会引起检测，USB调试过于明显

adb连mumu不需要开USB调试啊
