### ISSUE TITLE
请问大佬，这个报错有办法解决么？

### ISSUE THREAD

**Issue by Kuroneko0420** [NeutrinoC/Auto_GirlsFrontline#5]
C:\WINDOWS\system32>F:\Auto_GirlsFrontline-master\auto8_1n\auto8_1n.py
>>> 开始操作,现在是 2020-05-26 13:32:00.039919

Traceback (most recent call last):
  File "F:\Auto_GirlsFrontline-master\auto8_1n\auto8_1n.py", line 676, in <module>
    if isInMap():
  File "F:\Auto_GirlsFrontline-master\auto8_1n\auto8_1n.py", line 287, in isInMap
    return imageCompare(initImage,capImage)
  File "F:\Auto_GirlsFrontline-master\auto8_1n\auto8_1n.py", line 255, in imageCompare
    gray_img1 = cv2.cvtColor(img1, cv2.COLOR_BGR2GRAY)
cv2.error: OpenCV(4.2.0) D:\Build\OpenCV\opencv-4.2.0\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'

这个是在cmd下面运行的，我下载的opencv、skimage库版本跟您说的相同，用的蓝mumu，分辨率也跟您说的一样，就是不知道哪出错了

**Comment by NeutrinoC** [comment]
看这个报错就是抓取的截图不存在，或者是抓取失败，至于为什么失败可能的原因有很多，我只能给出几个排查方向:1.是否是管理员模式运行cmd；2.启动程序时是否已经启动模拟器且显示在桌面上

顺带一提，因为这两周活动频繁，ym不断地在调整UI界面，所以目前上传的程序里面抓取截图的位置都已经不对了需要调整，就是说不能用了(和报错无关)，我将在明晚游戏更新后对程序进行更新维护

**Comment by NeutrinoC** [comment]
说错了，是后天才更新

**Comment by Kuroneko0420** [comment]
![4{YBUH01 {8LJTL6{FA00M0](https://user-images.githubusercontent.com/52948727/82962774-c5a4c280-9ff3-11ea-9a28-ed516316fbf8.png)
ide运行出现了个这个，不知道为什么家里的台式机能好好运行，我笔记本就不太行，估计是python的原因，我卸载重装了一下python还是不行
谢谢大佬了，以后也只能靠大佬的脚本过日子了（滑稽）

**Comment by Kuroneko0420** [comment]
原因找到了，是因为电脑比例是125调成100就可以了
