### ISSUE TITLE
关于地图坐标定位

### ISSUE THREAD

**Issue by GiGaFotress** [NeutrinoC/Auto_GirlsFrontline#8]
关于指挥部/机场等的定位还是使用的固定坐标方式？我使用autojs试了一下，多次缩放有时候没到位，是否可以考虑走图像识别指挥部/机场的路子？

**Comment by NeutrinoC** [comment]
确实目前用的是固定坐标的方式，因为非常地简单方便。走图像的方法应该也行，比方说霍夫圆检测或者是用yolo神经网络之类的，但是就会比较麻烦而且吃配置，所以我个人还是倾向于用简单的固定坐标的方法。你说的这个缩放不到位我没遇到过所以不清楚是什么原因，不过多缩放几次保证能够到位的话应该就能解决这个问题了吧，比方说我所有的缩放操作都是有冗余的，就是为了避免这个不到位的情况。

**Comment by NeutrinoC** [comment]
我以前在做auto4_6的时候用过霍夫圆检测的方法定位路径点，确实可行的，速度也还可以，后来不记得具体什么原因反正是放弃了这个方法，如果你有兴趣的话可以试试这个方法

**Comment by GiGaFotress** [comment]
看了一眼霍夫圆的文档分辨出来的只是所有的路径点，要确定主基地的坐标还需要进一步的处理。。。在低分辨率下鉴别机场/HQ之类的蓝色图标都很容易混

**Comment by GiGaFotress** [comment]
怪怪的，在地图上缩放后下拉，有时候就是差100左右y没有拉下来

**Comment by NeutrinoC** [comment]
你用的auto.js应该不是在模拟器上跑的了吧？我自己用了几个月了，并没有碰到过这种问题，可能是平台差异的原因导致的？说来惭愧，我对这个auto.js了解甚少，可能帮不到你

**Comment by GiGaFotress** [comment]
不，没啥关系，我也是刚上手，叉子我都刷出来了，脚本还没写完2333
在实机上跑的，我准备把下拉加到3个循环试试

**Comment by GiGaFotress** [comment]
叉子EX我搞定了，还是传统坐标方式，识图能力范围外,仓库处理还没搞的，先抛出个异常退出脚本人手处理，摸了摸了
