### ISSUE TITLE
炸狗报错

### ISSUE THREAD

**Issue by nazhendenb** [NeutrinoC/Auto_GirlsFrontline#9]
![image](https://user-images.githubusercontent.com/36919867/89725015-22cde300-da3d-11ea-845b-220e86998ee6.png)

1.5倍经验之后就再也没练过级（其实是建造太多了没弹粮了），今天准备炸狗的时候报错了，删除原文件夹用git clone重新下载一遍还是一样的报错，见上图

**Comment by NeutrinoC** [comment]
这个是在修改鼠标位置的时候出错，应该是你没有以管理员模式运行造成的，我测试过了的，不以管理员模式运行就会报这个错误

**Comment by nazhendenb** [comment]
> 这个是在修改鼠标位置的时候出错，应该是你没有以管理员模式运行造成的，我测试过了的，不以管理员模式运行就会报这个错误

确实忘了用管理员模式，太长时间不用，姿势都忘了。
你那边的重启游戏没出过问题吗？我就没重启成功过，睡一觉起来发现一直在打印重启游戏，但是界面就停留在模拟器页面

**Comment by NeutrinoC** [comment]
我的重启游戏没问题的，这样解释吧，我的程序都是以点击动作实现的，所以这个重启游戏也是关闭少钱标签后在模拟器桌面点击少钱图标，所以这个点击的位置要对好，我默认的是把少钱图标放在了模拟器桌面第一行第一列，如果你没放在哪自然启动不了。如果不是这个原因那就要看具体是什么情况了

**Comment by NeutrinoC** [comment]
![TIM截图20200811095408](https://user-images.githubusercontent.com/35862168/89848318-ae1fb380-dbb8-11ea-81be-e7e17867bbc7.png)
就像这个样子

**Comment by zzzcy-868** [comment]
会不会是不同服的，像b服的游戏图标就跟官服的不一样。我就是b服的，而且不知道为什么有时候更换分辨率后，模拟器的桌面背景位置还会变（“少女前线”后面的那条斜线），每次重新更换预存图片就好了。
